// <auto-generated />
namespace PurchaseRequestSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixedpurchaserequestnotnulls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedpurchaserequestnotnulls));
        
        string IMigrationMetadata.Id
        {
            get { return "201803281618408_fixed purchaserequest not nulls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
